apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.example.com
  labels:
    app: cert-manager-webhook-etcd
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/cert-manager-webhook-etcd-webhook-tls"
spec:
  group: acme.example.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-etcd
    namespace: cert-manager
  version: v1alpha1
---
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-etcd-selfsign
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-etcd
spec:
  selfSigned: {}
---
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-etcd-ca
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-etcd
spec:
  secretName: cert-manager-webhook-etcd-ca
  duration: 43800h # 5y
  issuerRef:
    name: cert-manager-webhook-etcd-selfsign
  commonName: "ca.cert-manager-webhook-etcd.cert-manager"
  isCA: true
---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-etcd-ca
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-etcd
spec:
  ca:
    secretName: cert-manager-webhook-etcd-ca
---
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-etcd-webhook-tls
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-etcd
spec:
  secretName: cert-manager-webhook-etcd-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: cert-manager-webhook-etcd-ca
  dnsNames:
    - cert-manager-webhook-etcd
    - cert-manager-webhook-etcd.cert-manager
    - cert-manager-webhook-etcd.cert-manager.svc
    - cert-manager-webhook-etcd.cert-manager.svc.cluster.local
