apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-etcd
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-etcd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-etcd
  labels:
    app: cert-manager-webhook-etcd
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-etcd
  labels:
    app: cert-manager-webhook-etcd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-etcd
subjects:
  - kind: ServiceAccount
    name: cert-manager-webhook-etcd
    namespace: cert-manager
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# temporary CA cert-manager generates automatically. This is used for the apiserver
# to be able to validate the webhook's serving certificate.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-etcd:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: cert-manager-webhook-etcd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: cert-manager-webhook-etcd
    namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-etcd:auth-delegator
  labels:
    app: cert-manager-webhook-etcd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: cert-manager-webhook-etcd
    namespace: cert-manager
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-etcd:domain-solver
  labels:
    app: cert-manager-webhook-etcd
rules:
  - apiGroups:
      - acme.example.com
    resources:
      - '*'
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-etcd:domain-solver
  labels:
    app: cert-manager-webhook-etcd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-etcd:domain-solver
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
